# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true


# Run R expressions
  R-expr:
    runs-on: ubuntu-latest
    name: run-R-expr
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - run: echo $GITHUB_WORKSPACE
      - run: |
          R -e 'print("a");
          # -e flag for "run R expression"
          df <- data.frame(x = 1:10);
          head(df)'


# R expressions on multiple R versions
  R-expr-multi-ver:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '3.6.1', '4.1.2', '4.2.0' ]
    name: R ${{ matrix.R }} ver-test
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - run: Rscript -e 'print(sessionInfo()$R.version$version.string)'

# Run bash commands in terminal
  Greetings:
    runs-on: ubuntu-latest
    name: hello-where-am-i
    steps:
      - uses: actions/checkout@v2
      - run: echo "Multiple run clause"
      - run: |
         echo "Hello"
         echo "Current workdir is:"
         echo $GITHUB_WORKSPACE
         echo "$(pwd)"
         ls -la
