on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

name: R-script
jobs:

  install-R-pkg:
    runs-on: macOS-latest
    name: install-R-pkg
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.1.2'
      - run: |
          Rscript $(pwd)/exec/install_script.R
